# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stocksUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer

import getStocks








class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.nameList = set()  # this will be a set of non repeated stock names that have been in the top 25 movers section
        self.stockpile = []  # list containing all stock objects
        self.stockpileNames = []  # list containing names of stock pile in order

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 595)
        MainWindow.setStyleSheet("background-color: rgb(62, 62, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 50, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(179, 30, 621, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 12pt \"OCR A Extended\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.stockTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.stockTable.setAutoFillBackground(False)
        self.stockTable.setStyleSheet("QScrollBar:vertical{\n"
"    \n"
"\n"
"    background-color: rgb(52, 52, 52);\n"
"}\n"
"\n"
"QTableWidget{\n"
"color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QTableWidget:pressed{\n"
"color: rgb(0, 255, 0);\n"
"}\n"
"")
        self.stockTable.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stockTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stockTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stockTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.stockTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stockTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.stockTable.setGridStyle(QtCore.Qt.SolidLine)
        self.stockTable.setCornerButtonEnabled(True)
        self.stockTable.setRowCount(25)
        self.stockTable.setColumnCount(6)
        self.stockTable.setObjectName("stockTable")

        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setText("Enter")
        self.button.move(40,60)
        self.button.setStyleSheet("color: rgb(0, 170, 0);\n"
                                 "font: 12pt \"OCR A Extended\";\n"
                                  "background-color: rgb(50,50,50);")
        self.button.clicked.connect(self.button_pressed)



        for i in range(25):
            for j in range(6):

                item = QtWidgets.QTableWidgetItem()
                self.stockTable.setItem(i,j, item)

        self.stockTable.horizontalHeader().setVisible(False)
        self.stockTable.horizontalHeader().setCascadingSectionResizes(False)
        self.stockTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.stockTable)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(11, 31, 133, 20))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    \n"
"    background-color:  rgb(86, 86, 86);\n"
"    border: 1px solid black;\n"
"    font: 8pt \"OCR A Extended\";\n"
"    color: rgb(33, 33, 33);\n"
"    \n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    background-color: rgb(136, 136, 136);\n"
"    border: 1px black ;\n"
"    font: 8pt \"OCR A Extended\";\n"
"    color: rgb(0, 255, 0);\n"
"\n"
"}\n"
"")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit.setObjectName("lineEdit")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer = QTimer()
        self.timer.timeout.connect(self.updateItems)
        self.timer.start(10000)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TopMovers"))
        self.stockTable.setSortingEnabled(False)


        __sortingEnabled = self.stockTable.isSortingEnabled()
        self.stockTable.setSortingEnabled(False)
        self.stockTable.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setText(_translate("MainWindow", "Enter Stock Symbol"))


    def updateItems(self):
        _translate = QtCore.QCoreApplication.translate

        data = getStocks.getStockData(self.nameList,self.stockpile,self.stockpileNames)
        stocks = data[1]
        rowPosition = self.stockTable.rowCount()

        if len(data[0]) > rowPosition:

            for x in range(len(data[0]) - rowPosition):
                curr = self.stockTable.rowCount()
                self.stockTable.insertRow(curr)
                for i in range(6):
                    item = QtWidgets.QTableWidgetItem()

                    self.stockTable.setItem(curr, i, item)

        sortedStocks = sorted(self.stockpile, key=lambda s: s.getPercent(), reverse=True)

        for i,stock in enumerate(sortedStocks):
            for j,items in enumerate(stock.getAll()):
                self.stockTable.item(i, j).setText(_translate("MainWindow", str(items)))



        self.nameList = data[0]
        self.stockpile = stocks
        self.stockpileNames = data[2]


    def button_pressed(self):
        _translate = QtCore.QCoreApplication.translate
        name = self.lineEdit.text().upper()
        data = getStocks.getWebData(f"https://finance.yahoo.com/quote/{name}", "Fw(b) Fz(36px) Mb(-4px) D(ib)",
                                    "Fw(500) Pstart(8px) Fz(24px)",
                                    "Fw(500) Pstart(8px) Fz(24px)")

        if data != []:

            s = getStocks.stock(name, data[0], data[1], float(data[2][2:(len(data[2]) - 2)].replace(",", '', 1)), 0, 0)
            self.stockpile.append(s)
            self.stockpileNames.append(name)
            self.nameList.add(name)
            self.lineEdit.setText(_translate("MainWindow", " "))
        else:
            self.lineEdit.setText(_translate("MainWindow", "Invalid Symbol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())


